// Code generated by qtc from "box.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line box.qtpl:1
package multiagentspec

//line box.qtpl:3
import "fmt"

//line box.qtpl:4
import "strings"

//line box.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line box.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line box.qtpl:7
const qtplBoxWidth = 78

//line box.qtpl:10
func StreamBoxReport(qw422016 *qt422016.Writer, report *TeamReport) {
//line box.qtpl:10
	qw422016.N().S(`
`)
//line box.qtpl:11
	streamboxHeader(qw422016)
//line box.qtpl:11
	qw422016.N().S(`
`)
//line box.qtpl:12
	streamboxCenterLine(qw422016, report.EffectiveTitle())
//line box.qtpl:12
	qw422016.N().S(`
`)
//line box.qtpl:13
	streamboxSeparator(qw422016)
//line box.qtpl:13
	qw422016.N().S(`
`)
//line box.qtpl:14
	if len(report.SummaryBlocks) > 0 {
//line box.qtpl:14
		qw422016.N().S(`
`)
//line box.qtpl:15
		streamboxRenderBlocks(qw422016, report.SummaryBlocks)
//line box.qtpl:15
		qw422016.N().S(`
`)
//line box.qtpl:16
		streamboxSeparator(qw422016)
//line box.qtpl:16
		qw422016.N().S(`
`)
//line box.qtpl:17
	} else {
//line box.qtpl:17
		qw422016.N().S(`
`)
//line box.qtpl:18
		streamboxPaddedLine(qw422016, fmt.Sprintf("Project: %s", report.Project))
//line box.qtpl:18
		qw422016.N().S(`
`)
//line box.qtpl:19
		streamboxPaddedLine(qw422016, fmt.Sprintf("Target:  %s", report.Target))
//line box.qtpl:19
		qw422016.N().S(`
`)
//line box.qtpl:20
		if len(report.Tags) > 0 {
//line box.qtpl:20
			qw422016.N().S(`
`)
//line box.qtpl:21
			streamboxPaddedLine(qw422016, "Tags:")
//line box.qtpl:21
			qw422016.N().S(`
`)
//line box.qtpl:22
			streamboxRenderTags(qw422016, report.Tags)
//line box.qtpl:22
			qw422016.N().S(`
`)
//line box.qtpl:23
		}
//line box.qtpl:23
		qw422016.N().S(`
`)
//line box.qtpl:24
		streamboxSeparator(qw422016)
//line box.qtpl:24
		qw422016.N().S(`
`)
//line box.qtpl:25
	}
//line box.qtpl:25
	qw422016.N().S(`
`)
//line box.qtpl:26
	streamboxPaddedLine(qw422016, report.Phase)
//line box.qtpl:26
	qw422016.N().S(`
`)
//line box.qtpl:27
	for _, team := range report.Teams {
//line box.qtpl:27
		qw422016.N().S(`
`)
//line box.qtpl:28
		streamboxSeparator(qw422016)
//line box.qtpl:28
		qw422016.N().S(`
`)
//line box.qtpl:29
		streamboxTeamHeader(qw422016, team)
//line box.qtpl:29
		qw422016.N().S(`
`)
//line box.qtpl:30
		for _, task := range team.Tasks {
//line box.qtpl:30
			qw422016.N().S(`
`)
//line box.qtpl:31
			streamboxTaskLine(qw422016, task)
//line box.qtpl:31
			qw422016.N().S(`
`)
//line box.qtpl:32
		}
//line box.qtpl:32
		qw422016.N().S(`
`)
//line box.qtpl:33
		if len(team.ContentBlocks) > 0 {
//line box.qtpl:33
			qw422016.N().S(`
`)
//line box.qtpl:34
			streamboxRenderBlocks(qw422016, team.ContentBlocks)
//line box.qtpl:34
			qw422016.N().S(`
`)
//line box.qtpl:35
		}
//line box.qtpl:35
		qw422016.N().S(`
`)
//line box.qtpl:36
	}
//line box.qtpl:36
	qw422016.N().S(`
`)
//line box.qtpl:37
	if len(report.FooterBlocks) > 0 {
//line box.qtpl:37
		qw422016.N().S(`
`)
//line box.qtpl:38
		streamboxSeparator(qw422016)
//line box.qtpl:38
		qw422016.N().S(`
`)
//line box.qtpl:39
		streamboxRenderBlocks(qw422016, report.FooterBlocks)
//line box.qtpl:39
		qw422016.N().S(`
`)
//line box.qtpl:40
	}
//line box.qtpl:40
	qw422016.N().S(`
`)
//line box.qtpl:41
	streamboxSeparator(qw422016)
//line box.qtpl:41
	qw422016.N().S(`
`)
//line box.qtpl:42
	streamboxCenterLine(qw422016, report.FinalMessage())
//line box.qtpl:42
	qw422016.N().S(`
`)
//line box.qtpl:43
	streamboxFooter(qw422016)
//line box.qtpl:43
	qw422016.N().S(`
`)
//line box.qtpl:44
}

//line box.qtpl:44
func WriteBoxReport(qq422016 qtio422016.Writer, report *TeamReport) {
//line box.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:44
	StreamBoxReport(qw422016, report)
//line box.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:44
}

//line box.qtpl:44
func BoxReport(report *TeamReport) string {
//line box.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:44
	WriteBoxReport(qb422016, report)
//line box.qtpl:44
	qs422016 := string(qb422016.B)
//line box.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:44
	return qs422016
//line box.qtpl:44
}

//line box.qtpl:46
func streamboxHeader(qw422016 *qt422016.Writer) {
//line box.qtpl:46
	qw422016.N().S(`
╔`)
//line box.qtpl:47
	qw422016.E().S(strings.Repeat("═", qtplBoxWidth))
//line box.qtpl:47
	qw422016.N().S(`╗
`)
//line box.qtpl:48
}

//line box.qtpl:48
func writeboxHeader(qq422016 qtio422016.Writer) {
//line box.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:48
	streamboxHeader(qw422016)
//line box.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:48
}

//line box.qtpl:48
func boxHeader() string {
//line box.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:48
	writeboxHeader(qb422016)
//line box.qtpl:48
	qs422016 := string(qb422016.B)
//line box.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:48
	return qs422016
//line box.qtpl:48
}

//line box.qtpl:50
func streamboxSeparator(qw422016 *qt422016.Writer) {
//line box.qtpl:50
	qw422016.N().S(`
╠`)
//line box.qtpl:51
	qw422016.E().S(strings.Repeat("═", qtplBoxWidth))
//line box.qtpl:51
	qw422016.N().S(`╣
`)
//line box.qtpl:52
}

//line box.qtpl:52
func writeboxSeparator(qq422016 qtio422016.Writer) {
//line box.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:52
	streamboxSeparator(qw422016)
//line box.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:52
}

//line box.qtpl:52
func boxSeparator() string {
//line box.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:52
	writeboxSeparator(qb422016)
//line box.qtpl:52
	qs422016 := string(qb422016.B)
//line box.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:52
	return qs422016
//line box.qtpl:52
}

//line box.qtpl:54
func streamboxFooter(qw422016 *qt422016.Writer) {
//line box.qtpl:54
	qw422016.N().S(`
╚`)
//line box.qtpl:55
	qw422016.E().S(strings.Repeat("═", qtplBoxWidth))
//line box.qtpl:55
	qw422016.N().S(`╝
`)
//line box.qtpl:56
}

//line box.qtpl:56
func writeboxFooter(qq422016 qtio422016.Writer) {
//line box.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:56
	streamboxFooter(qw422016)
//line box.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:56
}

//line box.qtpl:56
func boxFooter() string {
//line box.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:56
	writeboxFooter(qb422016)
//line box.qtpl:56
	qs422016 := string(qb422016.B)
//line box.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:56
	return qs422016
//line box.qtpl:56
}

//line box.qtpl:58
func streamboxCenterLine(qw422016 *qt422016.Writer, text string) {
//line box.qtpl:58
	qw422016.N().S(`
`)
//line box.qtpl:60
	visualLen := boxVisualLength(text)
	padding := qtplBoxWidth - visualLen
	if padding < 0 {
		padding = 0
	}
	left := padding / 2
	right := padding - left

//line box.qtpl:67
	qw422016.N().S(`
║`)
//line box.qtpl:68
	qw422016.E().S(strings.Repeat(" ", left))
//line box.qtpl:68
	qw422016.E().S(text)
//line box.qtpl:68
	qw422016.E().S(strings.Repeat(" ", right))
//line box.qtpl:68
	qw422016.N().S(`║
`)
//line box.qtpl:69
}

//line box.qtpl:69
func writeboxCenterLine(qq422016 qtio422016.Writer, text string) {
//line box.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:69
	streamboxCenterLine(qw422016, text)
//line box.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:69
}

//line box.qtpl:69
func boxCenterLine(text string) string {
//line box.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:69
	writeboxCenterLine(qb422016, text)
//line box.qtpl:69
	qs422016 := string(qb422016.B)
//line box.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:69
	return qs422016
//line box.qtpl:69
}

//line box.qtpl:71
func streamboxPaddedLine(qw422016 *qt422016.Writer, text string) {
//line box.qtpl:71
	qw422016.N().S(`
`)
//line box.qtpl:73
	visualLen := boxVisualLength(text)
	padding := qtplBoxWidth - visualLen - 1
	if padding < 0 {
		padding = 0
	}

//line box.qtpl:78
	qw422016.N().S(`
║ `)
//line box.qtpl:79
	qw422016.E().S(text)
//line box.qtpl:79
	qw422016.E().S(strings.Repeat(" ", padding))
//line box.qtpl:79
	qw422016.N().S(`║
`)
//line box.qtpl:80
}

//line box.qtpl:80
func writeboxPaddedLine(qq422016 qtio422016.Writer, text string) {
//line box.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:80
	streamboxPaddedLine(qw422016, text)
//line box.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:80
}

//line box.qtpl:80
func boxPaddedLine(text string) string {
//line box.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:80
	writeboxPaddedLine(qb422016, text)
//line box.qtpl:80
	qs422016 := string(qb422016.B)
//line box.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:80
	return qs422016
//line box.qtpl:80
}

//line box.qtpl:82
func streamboxTeamHeader(qw422016 *qt422016.Writer, team TeamSection) {
//line box.qtpl:82
	qw422016.N().S(`
`)
//line box.qtpl:84
	text := boxFormatTeamHeader(team)

//line box.qtpl:85
	qw422016.N().S(`
`)
//line box.qtpl:86
	streamboxPaddedLine(qw422016, text)
//line box.qtpl:86
	qw422016.N().S(`
`)
//line box.qtpl:87
}

//line box.qtpl:87
func writeboxTeamHeader(qq422016 qtio422016.Writer, team TeamSection) {
//line box.qtpl:87
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:87
	streamboxTeamHeader(qw422016, team)
//line box.qtpl:87
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:87
}

//line box.qtpl:87
func boxTeamHeader(team TeamSection) string {
//line box.qtpl:87
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:87
	writeboxTeamHeader(qb422016, team)
//line box.qtpl:87
	qs422016 := string(qb422016.B)
//line box.qtpl:87
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:87
	return qs422016
//line box.qtpl:87
}

//line box.qtpl:89
func streamboxTaskLine(qw422016 *qt422016.Writer, task TaskResult) {
//line box.qtpl:89
	qw422016.N().S(`
`)
//line box.qtpl:91
	line := boxFormatTaskLine(task)

//line box.qtpl:92
	qw422016.N().S(`
`)
//line box.qtpl:93
	streamboxPaddedLine(qw422016, line)
//line box.qtpl:93
	qw422016.N().S(`
`)
//line box.qtpl:94
}

//line box.qtpl:94
func writeboxTaskLine(qq422016 qtio422016.Writer, task TaskResult) {
//line box.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:94
	streamboxTaskLine(qw422016, task)
//line box.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:94
}

//line box.qtpl:94
func boxTaskLine(task TaskResult) string {
//line box.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:94
	writeboxTaskLine(qb422016, task)
//line box.qtpl:94
	qs422016 := string(qb422016.B)
//line box.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:94
	return qs422016
//line box.qtpl:94
}

//line box.qtpl:96
func streamboxRenderTags(qw422016 *qt422016.Writer, tags map[string]string) {
//line box.qtpl:96
	qw422016.N().S(`
`)
//line box.qtpl:98
	lines := boxFormatTags(tags)

//line box.qtpl:99
	qw422016.N().S(`
`)
//line box.qtpl:100
	for _, line := range lines {
//line box.qtpl:100
		qw422016.N().S(`
`)
//line box.qtpl:101
		streamboxPaddedLine(qw422016, line)
//line box.qtpl:101
		qw422016.N().S(`
`)
//line box.qtpl:102
	}
//line box.qtpl:102
	qw422016.N().S(`
`)
//line box.qtpl:103
}

//line box.qtpl:103
func writeboxRenderTags(qq422016 qtio422016.Writer, tags map[string]string) {
//line box.qtpl:103
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:103
	streamboxRenderTags(qw422016, tags)
//line box.qtpl:103
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:103
}

//line box.qtpl:103
func boxRenderTags(tags map[string]string) string {
//line box.qtpl:103
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:103
	writeboxRenderTags(qb422016, tags)
//line box.qtpl:103
	qs422016 := string(qb422016.B)
//line box.qtpl:103
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:103
	return qs422016
//line box.qtpl:103
}

//line box.qtpl:105
func streamboxRenderBlocks(qw422016 *qt422016.Writer, blocks []ContentBlock) {
//line box.qtpl:105
	qw422016.N().S(`
`)
//line box.qtpl:106
	for _, block := range blocks {
//line box.qtpl:106
		qw422016.N().S(`
`)
//line box.qtpl:107
		streamboxRenderBlock(qw422016, block)
//line box.qtpl:107
		qw422016.N().S(`
`)
//line box.qtpl:108
	}
//line box.qtpl:108
	qw422016.N().S(`
`)
//line box.qtpl:109
}

//line box.qtpl:109
func writeboxRenderBlocks(qq422016 qtio422016.Writer, blocks []ContentBlock) {
//line box.qtpl:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:109
	streamboxRenderBlocks(qw422016, blocks)
//line box.qtpl:109
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:109
}

//line box.qtpl:109
func boxRenderBlocks(blocks []ContentBlock) string {
//line box.qtpl:109
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:109
	writeboxRenderBlocks(qb422016, blocks)
//line box.qtpl:109
	qs422016 := string(qb422016.B)
//line box.qtpl:109
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:109
	return qs422016
//line box.qtpl:109
}

//line box.qtpl:111
func streamboxRenderBlock(qw422016 *qt422016.Writer, block ContentBlock) {
//line box.qtpl:111
	qw422016.N().S(`
`)
//line box.qtpl:112
	if block.Title != "" {
//line box.qtpl:112
		qw422016.N().S(`
`)
//line box.qtpl:113
		streamboxPaddedLine(qw422016, block.Title)
//line box.qtpl:113
		qw422016.N().S(`
`)
//line box.qtpl:114
	}
//line box.qtpl:114
	qw422016.N().S(`
`)
//line box.qtpl:116
	lines := boxFormatBlock(block)

//line box.qtpl:117
	qw422016.N().S(`
`)
//line box.qtpl:118
	for _, line := range lines {
//line box.qtpl:118
		qw422016.N().S(`
`)
//line box.qtpl:119
		streamboxPaddedLine(qw422016, line)
//line box.qtpl:119
		qw422016.N().S(`
`)
//line box.qtpl:120
	}
//line box.qtpl:120
	qw422016.N().S(`
`)
//line box.qtpl:121
}

//line box.qtpl:121
func writeboxRenderBlock(qq422016 qtio422016.Writer, block ContentBlock) {
//line box.qtpl:121
	qw422016 := qt422016.AcquireWriter(qq422016)
//line box.qtpl:121
	streamboxRenderBlock(qw422016, block)
//line box.qtpl:121
	qt422016.ReleaseWriter(qw422016)
//line box.qtpl:121
}

//line box.qtpl:121
func boxRenderBlock(block ContentBlock) string {
//line box.qtpl:121
	qb422016 := qt422016.AcquireByteBuffer()
//line box.qtpl:121
	writeboxRenderBlock(qb422016, block)
//line box.qtpl:121
	qs422016 := string(qb422016.B)
//line box.qtpl:121
	qt422016.ReleaseByteBuffer(qb422016)
//line box.qtpl:121
	return qs422016
//line box.qtpl:121
}

//line box.qtpl:124
func boxVisualLength(s string) int {
	length := 0
	for _, r := range s {
		if r >= 0x1F300 && r <= 0x1FAFF {
			length += 2
		} else if r >= 0x2600 && r <= 0x27BF {
			length += 2
		} else {
			length++
		}
	}
	return length
}

func boxFormatTeamHeader(team TeamSection) string {
	icon := team.Status.Icon()
	if team.Verdict != "" {
		return fmt.Sprintf("%s %s — %s — %s", icon, team.Name, team.Status, team.Verdict)
	}
	return fmt.Sprintf("%s %s — %s", icon, team.Name, team.Status)
}

func boxFormatTaskLine(task TaskResult) string {
	id := task.ID
	if len(id) > 24 {
		id = id[:21] + "..."
	}
	icon := task.Status.Icon()
	statusText := string(task.Status)
	if task.Severity != "" {
		statusText = fmt.Sprintf("%s [%s]", statusText, task.Severity)
	}
	detail := task.Detail
	maxDetail := qtplBoxWidth - 45
	if len(detail) > maxDetail {
		detail = detail[:maxDetail-3] + "..."
	}
	return fmt.Sprintf("  %-24s %s %-15s %s", id, icon, statusText, detail)
}

func boxFormatTags(tags map[string]string) []string {
	keys := make([]string, 0, len(tags))
	for k := range tags {
		keys = append(keys, k)
	}
	// Sort keys
	for i := 0; i < len(keys)-1; i++ {
		for j := i + 1; j < len(keys); j++ {
			if keys[j] < keys[i] {
				keys[i], keys[j] = keys[j], keys[i]
			}
		}
	}
	lines := make([]string, len(keys))
	for i, k := range keys {
		lines[i] = fmt.Sprintf("  %s: %s", k, tags[k])
	}
	return lines
}

func boxFormatBlock(block ContentBlock) []string {
	var lines []string
	switch block.Type {
	case ContentBlockKVPairs:
		for _, pair := range block.Pairs {
			if pair.Icon != "" {
				lines = append(lines, fmt.Sprintf("%s %s: %s", pair.Icon, pair.Key, pair.Value))
			} else {
				lines = append(lines, fmt.Sprintf("%s: %s", pair.Key, pair.Value))
			}
		}
	case ContentBlockList:
		for _, item := range block.Items {
			icon := item.EffectiveIcon()
			if icon != "" {
				lines = append(lines, fmt.Sprintf("%s %s", icon, item.Text))
			} else {
				lines = append(lines, fmt.Sprintf("  %s", item.Text))
			}
		}
	case ContentBlockText:
		lines = boxWrapText(block.Content, qtplBoxWidth-2)
	case ContentBlockTable:
		lines = boxFormatTable(block.Headers, block.Rows)
	case ContentBlockMetric:
		icon := block.Status.Icon()
		if block.Target != "" {
			lines = append(lines, fmt.Sprintf("%s %s: %s (target: %s)", icon, block.Label, block.Value, block.Target))
		} else {
			lines = append(lines, fmt.Sprintf("%s %s: %s", icon, block.Label, block.Value))
		}
	}
	return lines
}

func boxWrapText(content string, maxWidth int) []string {
	var lines []string
	words := strings.Fields(content)
	if len(words) == 0 {
		return lines
	}
	currentLine := ""
	for _, word := range words {
		if currentLine == "" {
			currentLine = word
		} else if len(currentLine)+1+len(word) <= maxWidth {
			currentLine += " " + word
		} else {
			lines = append(lines, currentLine)
			currentLine = word
		}
	}
	if currentLine != "" {
		lines = append(lines, currentLine)
	}
	return lines
}

func boxFormatTable(headers []string, rows [][]string) []string {
	var lines []string
	colWidths := make([]int, len(headers))
	for i, h := range headers {
		colWidths[i] = len(h)
	}
	for _, row := range rows {
		for i, cell := range row {
			if i < len(colWidths) && len(cell) > colWidths[i] {
				colWidths[i] = len(cell)
			}
		}
	}
	// Header
	headerParts := make([]string, len(headers))
	for i, h := range headers {
		headerParts[i] = fmt.Sprintf("%-*s", colWidths[i], h)
	}
	lines = append(lines, strings.Join(headerParts, " │ "))
	// Separator
	sepParts := make([]string, len(headers))
	for i := range headers {
		sepParts[i] = strings.Repeat("─", colWidths[i])
	}
	lines = append(lines, strings.Join(sepParts, "─┼─"))
	// Rows
	for _, row := range rows {
		rowParts := make([]string, len(headers))
		for i := range headers {
			cell := ""
			if i < len(row) {
				cell = row[i]
			}
			rowParts[i] = fmt.Sprintf("%-*s", colWidths[i], cell)
		}
		lines = append(lines, strings.Join(rowParts, " │ "))
	}
	return lines
}
