// Code generated by qtc from "narrative.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line narrative.qtpl:1
package multiagentspec

//line narrative.qtpl:3
import "sort"

//line narrative.qtpl:4
import "strings"

//line narrative.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line narrative.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line narrative.qtpl:6
func StreamNarrativeReport(qw422016 *qt422016.Writer, report *TeamReport) {
//line narrative.qtpl:6
	qw422016.N().S(`
---
title: "`)
//line narrative.qtpl:8
	qw422016.E().S(report.EffectiveTitle())
//line narrative.qtpl:8
	qw422016.N().S(`"
date: "`)
//line narrative.qtpl:9
	qw422016.E().S(report.GeneratedAt.Format("2006-01-02"))
//line narrative.qtpl:9
	qw422016.N().S(`"
---

# `)
//line narrative.qtpl:12
	qw422016.E().S(report.EffectiveTitle())
//line narrative.qtpl:12
	qw422016.N().S(`

**Project**: `)
//line narrative.qtpl:14
	qw422016.E().S(report.Project)
//line narrative.qtpl:14
	qw422016.N().S(`
**Version**: `)
//line narrative.qtpl:15
	qw422016.E().S(report.Version)
//line narrative.qtpl:15
	qw422016.N().S(`
**Phase**: `)
//line narrative.qtpl:16
	qw422016.E().S(report.Phase)
//line narrative.qtpl:16
	qw422016.N().S(`
**Overall Status**: `)
//line narrative.qtpl:17
	qw422016.E().S(narrativeStatusText(report.Status))
//line narrative.qtpl:17
	qw422016.N().S(`
`)
//line narrative.qtpl:18
	if len(report.Tags) > 0 {
//line narrative.qtpl:18
		qw422016.N().S(`

### Tags

`)
//line narrative.qtpl:22
		streamnarrativeRenderTags(qw422016, report.Tags)
//line narrative.qtpl:22
		qw422016.N().S(`
`)
//line narrative.qtpl:23
	}
//line narrative.qtpl:23
	qw422016.N().S(`
`)
//line narrative.qtpl:24
	if report.Summary != "" {
//line narrative.qtpl:24
		qw422016.N().S(`

## Executive Summary

`)
//line narrative.qtpl:28
		qw422016.E().S(report.Summary)
//line narrative.qtpl:28
		qw422016.N().S(`
`)
//line narrative.qtpl:29
	}
//line narrative.qtpl:29
	qw422016.N().S(`
`)
//line narrative.qtpl:30
	if len(report.SummaryBlocks) > 0 {
//line narrative.qtpl:30
		qw422016.N().S(`

## Overview

`)
//line narrative.qtpl:34
		streamnarrativeRenderBlocks(qw422016, report.SummaryBlocks)
//line narrative.qtpl:34
		qw422016.N().S(`
`)
//line narrative.qtpl:35
	}
//line narrative.qtpl:35
	qw422016.N().S(`

## Team Results
`)
//line narrative.qtpl:38
	for _, team := range report.Teams {
//line narrative.qtpl:38
		qw422016.N().S(`

### `)
//line narrative.qtpl:40
		qw422016.E().S(team.Name)
//line narrative.qtpl:40
		qw422016.N().S(`

**Status**: `)
//line narrative.qtpl:42
		qw422016.E().S(narrativeStatusText(team.Status))
//line narrative.qtpl:42
		qw422016.N().S(`
`)
//line narrative.qtpl:43
		if team.Verdict != "" {
//line narrative.qtpl:43
			qw422016.N().S(`
**Verdict**: `)
//line narrative.qtpl:44
			qw422016.E().S(team.Verdict)
//line narrative.qtpl:44
			qw422016.N().S(`
`)
//line narrative.qtpl:45
		}
//line narrative.qtpl:45
		qw422016.N().S(`
`)
//line narrative.qtpl:46
		if team.Narrative != nil && (team.Narrative.Problem != "" || team.Narrative.Analysis != "" || team.Narrative.Recommendation != "") {
//line narrative.qtpl:46
			qw422016.N().S(`
`)
//line narrative.qtpl:47
			if team.Narrative.Problem != "" {
//line narrative.qtpl:47
				qw422016.N().S(`

#### Problem

`)
//line narrative.qtpl:51
				qw422016.E().S(team.Narrative.Problem)
//line narrative.qtpl:51
				qw422016.N().S(`
`)
//line narrative.qtpl:52
			}
//line narrative.qtpl:52
			qw422016.N().S(`
`)
//line narrative.qtpl:53
			if team.Narrative.Analysis != "" {
//line narrative.qtpl:53
				qw422016.N().S(`

#### Analysis

`)
//line narrative.qtpl:57
				qw422016.E().S(team.Narrative.Analysis)
//line narrative.qtpl:57
				qw422016.N().S(`
`)
//line narrative.qtpl:58
			}
//line narrative.qtpl:58
			qw422016.N().S(`
`)
//line narrative.qtpl:59
			if team.Narrative.Recommendation != "" {
//line narrative.qtpl:59
				qw422016.N().S(`

#### Recommendation

`)
//line narrative.qtpl:63
				qw422016.E().S(team.Narrative.Recommendation)
//line narrative.qtpl:63
				qw422016.N().S(`
`)
//line narrative.qtpl:64
			}
//line narrative.qtpl:64
			qw422016.N().S(`
`)
//line narrative.qtpl:65
		}
//line narrative.qtpl:65
		qw422016.N().S(`
`)
//line narrative.qtpl:66
		if len(team.Tasks) > 0 {
//line narrative.qtpl:66
			qw422016.N().S(`

#### Tasks

| Task | Status | Severity | Detail |
| --- | --- | --- | --- |
`)
//line narrative.qtpl:72
			for _, task := range team.Tasks {
//line narrative.qtpl:72
				qw422016.N().S(`
| `)
//line narrative.qtpl:73
				qw422016.E().S(task.ID)
//line narrative.qtpl:73
				qw422016.N().S(` | `)
//line narrative.qtpl:73
				qw422016.E().S(narrativeStatusText(task.Status))
//line narrative.qtpl:73
				qw422016.N().S(` | `)
//line narrative.qtpl:73
				qw422016.E().S(task.Severity)
//line narrative.qtpl:73
				qw422016.N().S(` | `)
//line narrative.qtpl:73
				qw422016.E().S(task.Detail)
//line narrative.qtpl:73
				qw422016.N().S(` |
`)
//line narrative.qtpl:74
			}
//line narrative.qtpl:74
			qw422016.N().S(`
`)
//line narrative.qtpl:75
		}
//line narrative.qtpl:75
		qw422016.N().S(`
`)
//line narrative.qtpl:76
		if len(team.ContentBlocks) > 0 {
//line narrative.qtpl:76
			qw422016.N().S(`

#### Details

`)
//line narrative.qtpl:80
			streamnarrativeRenderBlocks(qw422016, team.ContentBlocks)
//line narrative.qtpl:80
			qw422016.N().S(`
`)
//line narrative.qtpl:81
		}
//line narrative.qtpl:81
		qw422016.N().S(`
`)
//line narrative.qtpl:82
	}
//line narrative.qtpl:82
	qw422016.N().S(`
`)
//line narrative.qtpl:83
	if len(report.FooterBlocks) > 0 {
//line narrative.qtpl:83
		qw422016.N().S(`

## Action Items

`)
//line narrative.qtpl:87
		streamnarrativeRenderBlocks(qw422016, report.FooterBlocks)
//line narrative.qtpl:87
		qw422016.N().S(`
`)
//line narrative.qtpl:88
	}
//line narrative.qtpl:88
	qw422016.N().S(`
`)
//line narrative.qtpl:89
	if report.Conclusion != "" {
//line narrative.qtpl:89
		qw422016.N().S(`

## Conclusion

`)
//line narrative.qtpl:93
		qw422016.E().S(report.Conclusion)
//line narrative.qtpl:93
		qw422016.N().S(`
`)
//line narrative.qtpl:94
	}
//line narrative.qtpl:94
	qw422016.N().S(`
`)
//line narrative.qtpl:95
}

//line narrative.qtpl:95
func WriteNarrativeReport(qq422016 qtio422016.Writer, report *TeamReport) {
//line narrative.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line narrative.qtpl:95
	StreamNarrativeReport(qw422016, report)
//line narrative.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line narrative.qtpl:95
}

//line narrative.qtpl:95
func NarrativeReport(report *TeamReport) string {
//line narrative.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
//line narrative.qtpl:95
	WriteNarrativeReport(qb422016, report)
//line narrative.qtpl:95
	qs422016 := string(qb422016.B)
//line narrative.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
//line narrative.qtpl:95
	return qs422016
//line narrative.qtpl:95
}

//line narrative.qtpl:97
func streamnarrativeRenderTags(qw422016 *qt422016.Writer, tags map[string]string) {
//line narrative.qtpl:97
	qw422016.N().S(`
`)
//line narrative.qtpl:99
	keys := make([]string, 0, len(tags))
	for k := range tags {
		keys = append(keys, k)
	}
	sort.Strings(keys)

//line narrative.qtpl:104
	qw422016.N().S(`
`)
//line narrative.qtpl:105
	for _, k := range keys {
//line narrative.qtpl:105
		qw422016.N().S(`
- **`)
//line narrative.qtpl:106
		qw422016.E().S(k)
//line narrative.qtpl:106
		qw422016.N().S(`**: `)
//line narrative.qtpl:106
		qw422016.E().S(tags[k])
//line narrative.qtpl:106
		qw422016.N().S(`
`)
//line narrative.qtpl:107
	}
//line narrative.qtpl:107
	qw422016.N().S(`
`)
//line narrative.qtpl:108
}

//line narrative.qtpl:108
func writenarrativeRenderTags(qq422016 qtio422016.Writer, tags map[string]string) {
//line narrative.qtpl:108
	qw422016 := qt422016.AcquireWriter(qq422016)
//line narrative.qtpl:108
	streamnarrativeRenderTags(qw422016, tags)
//line narrative.qtpl:108
	qt422016.ReleaseWriter(qw422016)
//line narrative.qtpl:108
}

//line narrative.qtpl:108
func narrativeRenderTags(tags map[string]string) string {
//line narrative.qtpl:108
	qb422016 := qt422016.AcquireByteBuffer()
//line narrative.qtpl:108
	writenarrativeRenderTags(qb422016, tags)
//line narrative.qtpl:108
	qs422016 := string(qb422016.B)
//line narrative.qtpl:108
	qt422016.ReleaseByteBuffer(qb422016)
//line narrative.qtpl:108
	return qs422016
//line narrative.qtpl:108
}

//line narrative.qtpl:110
func streamnarrativeRenderBlocks(qw422016 *qt422016.Writer, blocks []ContentBlock) {
//line narrative.qtpl:110
	qw422016.N().S(`
`)
//line narrative.qtpl:111
	for i, block := range blocks {
//line narrative.qtpl:111
		qw422016.N().S(`
`)
//line narrative.qtpl:112
		streamnarrativeRenderBlock(qw422016, block)
//line narrative.qtpl:112
		qw422016.N().S(`
`)
//line narrative.qtpl:113
		if i < len(blocks)-1 {
//line narrative.qtpl:113
			qw422016.N().S(`

`)
//line narrative.qtpl:115
		}
//line narrative.qtpl:115
		qw422016.N().S(`
`)
//line narrative.qtpl:116
	}
//line narrative.qtpl:116
	qw422016.N().S(`
`)
//line narrative.qtpl:117
}

//line narrative.qtpl:117
func writenarrativeRenderBlocks(qq422016 qtio422016.Writer, blocks []ContentBlock) {
//line narrative.qtpl:117
	qw422016 := qt422016.AcquireWriter(qq422016)
//line narrative.qtpl:117
	streamnarrativeRenderBlocks(qw422016, blocks)
//line narrative.qtpl:117
	qt422016.ReleaseWriter(qw422016)
//line narrative.qtpl:117
}

//line narrative.qtpl:117
func narrativeRenderBlocks(blocks []ContentBlock) string {
//line narrative.qtpl:117
	qb422016 := qt422016.AcquireByteBuffer()
//line narrative.qtpl:117
	writenarrativeRenderBlocks(qb422016, blocks)
//line narrative.qtpl:117
	qs422016 := string(qb422016.B)
//line narrative.qtpl:117
	qt422016.ReleaseByteBuffer(qb422016)
//line narrative.qtpl:117
	return qs422016
//line narrative.qtpl:117
}

//line narrative.qtpl:119
func streamnarrativeRenderBlock(qw422016 *qt422016.Writer, block ContentBlock) {
//line narrative.qtpl:119
	qw422016.N().S(`
`)
//line narrative.qtpl:120
	if block.Title != "" {
//line narrative.qtpl:120
		qw422016.N().S(`
**`)
//line narrative.qtpl:121
		qw422016.E().S(block.Title)
//line narrative.qtpl:121
		qw422016.N().S(`**

`)
//line narrative.qtpl:123
	}
//line narrative.qtpl:123
	qw422016.N().S(`
`)
//line narrative.qtpl:124
	switch block.Type {
//line narrative.qtpl:125
	case ContentBlockKVPairs:
//line narrative.qtpl:125
		qw422016.N().S(`
`)
//line narrative.qtpl:126
		for _, pair := range block.Pairs {
//line narrative.qtpl:126
			qw422016.N().S(`
- **`)
//line narrative.qtpl:127
			qw422016.E().S(pair.Key)
//line narrative.qtpl:127
			qw422016.N().S(`**: `)
//line narrative.qtpl:127
			qw422016.E().S(pair.Value)
//line narrative.qtpl:127
			qw422016.N().S(`
`)
//line narrative.qtpl:128
		}
//line narrative.qtpl:128
		qw422016.N().S(`
`)
//line narrative.qtpl:129
	case ContentBlockList:
//line narrative.qtpl:129
		qw422016.N().S(`
`)
//line narrative.qtpl:130
		for _, item := range block.Items {
//line narrative.qtpl:130
			qw422016.N().S(`
- `)
//line narrative.qtpl:131
			qw422016.E().S(item.Text)
//line narrative.qtpl:131
			qw422016.N().S(`
`)
//line narrative.qtpl:132
		}
//line narrative.qtpl:132
		qw422016.N().S(`
`)
//line narrative.qtpl:133
	case ContentBlockText:
//line narrative.qtpl:133
		qw422016.N().S(`
`)
//line narrative.qtpl:134
		qw422016.E().S(block.Content)
//line narrative.qtpl:134
		qw422016.N().S(`
`)
//line narrative.qtpl:135
	case ContentBlockTable:
//line narrative.qtpl:135
		qw422016.N().S(`
| `)
//line narrative.qtpl:136
		qw422016.E().S(strings.Join(block.Headers, " | "))
//line narrative.qtpl:136
		qw422016.N().S(` |
| `)
//line narrative.qtpl:137
		qw422016.E().S(narrativeTableSep(len(block.Headers)))
//line narrative.qtpl:137
		qw422016.N().S(` |
`)
//line narrative.qtpl:138
		for _, row := range block.Rows {
//line narrative.qtpl:138
			qw422016.N().S(`
| `)
//line narrative.qtpl:139
			qw422016.E().S(strings.Join(row, " | "))
//line narrative.qtpl:139
			qw422016.N().S(` |
`)
//line narrative.qtpl:140
		}
//line narrative.qtpl:140
		qw422016.N().S(`
`)
//line narrative.qtpl:141
	case ContentBlockMetric:
//line narrative.qtpl:141
		qw422016.N().S(`
- **`)
//line narrative.qtpl:142
		qw422016.E().S(block.Label)
//line narrative.qtpl:142
		qw422016.N().S(`**: `)
//line narrative.qtpl:142
		qw422016.E().S(block.Value)
//line narrative.qtpl:142
		if block.Target != "" {
//line narrative.qtpl:142
			qw422016.N().S(` (target: `)
//line narrative.qtpl:142
			qw422016.E().S(block.Target)
//line narrative.qtpl:142
			qw422016.N().S(`)`)
//line narrative.qtpl:142
		}
//line narrative.qtpl:142
		qw422016.N().S(` — `)
//line narrative.qtpl:142
		qw422016.E().S(narrativeStatusText(block.Status))
//line narrative.qtpl:142
		qw422016.N().S(`
`)
//line narrative.qtpl:143
	}
//line narrative.qtpl:143
	qw422016.N().S(`
`)
//line narrative.qtpl:144
}

//line narrative.qtpl:144
func writenarrativeRenderBlock(qq422016 qtio422016.Writer, block ContentBlock) {
//line narrative.qtpl:144
	qw422016 := qt422016.AcquireWriter(qq422016)
//line narrative.qtpl:144
	streamnarrativeRenderBlock(qw422016, block)
//line narrative.qtpl:144
	qt422016.ReleaseWriter(qw422016)
//line narrative.qtpl:144
}

//line narrative.qtpl:144
func narrativeRenderBlock(block ContentBlock) string {
//line narrative.qtpl:144
	qb422016 := qt422016.AcquireByteBuffer()
//line narrative.qtpl:144
	writenarrativeRenderBlock(qb422016, block)
//line narrative.qtpl:144
	qs422016 := string(qb422016.B)
//line narrative.qtpl:144
	qt422016.ReleaseByteBuffer(qb422016)
//line narrative.qtpl:144
	return qs422016
//line narrative.qtpl:144
}

//line narrative.qtpl:147
func narrativeStatusText(s Status) string {
	switch s {
	case StatusGo:
		return "PASS"
	case StatusWarn:
		return "WARNING"
	case StatusNoGo:
		return "FAIL"
	case StatusSkip:
		return "SKIP"
	default:
		return string(s)
	}
}

func narrativeTableSep(cols int) string {
	parts := make([]string, cols)
	for i := range parts {
		parts[i] = "---"
	}
	return strings.Join(parts, " | ")
}
